### PR TITLE
Closes #218 modified row merge (#219)

### LINKED ISSUE #218: Bug: axecute() returns error when same number of unapproved functions within multiple packages are used
### What happened?

Problem within `write_unapproved_functions` function. When it comes to printing out the unapproved packages/functions in the log file, it produces an error and stops if there are **two** unapproved packages with **two** unapproved functions **each**, within the corresponding R script that we are trying to axecute. This is also the case when there are **three** unapproved packages with **two** unapproved functions **each**. Other than that, it prints out any unapproved packages/functions just fine in the logs.

### Session Information

```
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] logrx_0.3.0 tidyr_1.3.1 dplyr_1.1.4

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       cli_3.6.2         rlang_1.1.3       stringi_1.8.3     purrr_1.0.2       renv_0.17.3      
 [7] promises_1.2.1    generics_0.1.3    shiny_1.8.0       xtable_1.8-4      glue_1.7.0        htmltools_0.5.7  
[13] httpuv_1.6.14     fansi_1.0.6       tibble_3.2.1      ellipsis_0.3.2    fastmap_1.1.1     lifecycle_1.0.4  
[19] stringr_1.5.1     compiler_4.3.0    miniUI_0.1.1.1    sessioninfo_1.2.2 Rcpp_1.0.12       pkgconfig_2.0.3  
[25] rstudioapi_0.15.0 later_1.3.2       tcltk_4.3.0       digest_0.6.34     R6_2.5.1          tidyselect_1.2.0 
[31] utf8_1.2.4        pillar_1.9.0      waiter_0.2.5      magrittr_2.0.3    withr_3.0.0       tools_4.3.0      
[37] mime_0.12    
```

### Reproducible Example

1. Create the `approved.rds` file containing the approved packages/functions within new Rstudio project called `exploratory` :
```
library(logrx)

approved_pkgs <- list(base = "All",
                      utils = 'All',
                      logrx = "All"
)

build_approved(approved_pkgs, file = file.path('C:/exploratory', "approved.rds"))

```

2. Add new option to the .Rprofile 
```
## Update the logrx.approved option
options(log.rx.approved = file.path('C:/exploratory', "approved.rds"))
```
3. Create new R script called `testing.R` to axecute. This contains the packages `dplyr` and `tidyr` which are unapproved, each of the packages using two functions: `mutate`, and `arrange` from `dplyr`, and `%>%` and `drop_na` from `tidyr`:
```
library(dplyr)
library(tidyr)

test_data<- iris
test_data <- tidyr::`%>%`(test_data, 
  mutate(new = Sepal.Length + Sepal.Width)) 

test_data <- tidyr::`%>%`(test_data, 
  arrange(new)) 

test_data <- tidyr::`%>%`(test_data,
  drop_na())
```
4. axecute the `testing.R` file:
`logrx::axecute('testing.R')`

5. This is then printed in the console, coming from the `write_unapproved_functions` function within `logrx`:
```
Error in `map2()`:
! Can't recycle `.x` (size 2) to match `.y` (size 4).
Run `rlang::last_trace()` to see where the error occurred.
```

### PR DESCRIPTION
**Pull request by nicholas-masel**
* modified row merge

### Thank you for your Pull Request! 

We have developed a Pull Request template to aid you and our reviewers.  Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the logrx codebase remains robust and consistent.  

### The spirit of logrx

While many packages to facilitate the logging of code already exist in the R ecosystem, it is hard to find a solution that works well for clinical programming applications. Many logging implementations are more implicit and rely on user input to create the log for the execution of a script. While this is useful for logging specific events of an application, in clinical programming a log has a set purpose.

logrx is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well as the environment that it happened in. We set out to create a flexible logging utility that could provide the necessary information to anyone reviewing the code execution so they can recreate the execution environment and run the code for themselves. Please make sure your Pull Request meets this **spirit of logrx**.

Please check off each taskbox as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `dev` branch until you have checked off each task.

- [x] The spirit of logrx is met in your Pull Request
- [x] Check that your Pull Request is targeting the dev branch, Pull Requests to master should use the [Release Pull Request Template](https://github.com/pharmaverse/logrx/blob/main/.github/PULL_REQUEST_TEMPLATE/release.md)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests.  Remember to remove any configured log objects at the end of every test using `log_remove()`.
- [x] Creation/updates to relevant roxygen headers and examples.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Run `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "Reference" page.
- [x] Update NEWS.md if the changes pertain to a user-facing function (i.e. it has an @export tag) or documentation aimed at users (rather than developers)
- [x] Address any updates needed for vignettes and/or templates
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Umm...the Update Branch has me a little worried.

**Comment by kodesiba** [comment]
> Umm...the Update Branch has me a little worried.

@bms63 what do you mean by this? If it's about the "bypass branch protections" I believe that is because of the windows R CMD check failing and if that's happening other places I'm happy to bypass them.

**Comment by kodesiba** [comment]
@bms63 sorry for the double tag but it looks like there was a merge commit added with the last merge to main so it is technically one commit ahead but it is just a merge commit.

**Comment by bms63** [comment]
Did this get sent to CRAN?

**Comment by bms63** [comment]
I wish these window checks would pass.  i think send from dev.  after it is live we can merge to main

**Comment by kodesiba** [comment]
@bms63 would it be worth switching to the admiralci action instead?  looks like most of the other packages in pharmaverse use that so we could go that direction instead of banging our heads against this wall

**Comment by bms63** [comment]
I'm hesitant to use admiral's CI as they are kind of complicated.  

Looking at `r-lib/actions` I see our version are behind...did a quick update to see if maybe that helps!?!

**Review by kodesiba — APPROVED** [review]

**Comment by kodesiba** [comment]
@bms63 @nicholas-masel I can get this sent off to CRAN this afternoon and we can merge this whenever

**Pull request merged**
